FROM node:22-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV NODE_ENV=development
ENV CI=true
RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps/web/package.json apps/web/package.json
COPY packages/backend/package.json packages/backend/package.json
COPY packages/inngest/package.json packages/inngest/package.json
COPY tooling/eslint/package.json tooling/eslint/package.json
COPY tooling/prettier/package.json tooling/prettier/package.json
COPY tooling/tsconfig/package.json tooling/tsconfig/package.json

COPY . .
RUN pnpm install --frozen-lockfile --config.confirmModulesPurge=false

CMD ["pnpm", "--filter", "@eboto/web", "dev", "--host", "0.0.0.0"]