packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@tanstack/react-query': 5.89.0
  '@types/node': 24.5.2
  '@types/react': 19.1.13
  '@types/react-dom': 19.1.9
  dayjs: 1.11.18
  eslint: 9.35.0
  inngest: 3.40.3
  prettier: 3.6.2
  react: 19.1.1
  react-dom: 19.1.1
  typescript: 5.9.2
  typescript-eslint: 8.39.0
  zod: 4.1.9
