packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@supabase/supabase-js': 2.56.1
  '@supabase/ssr': 0.7.0
  '@t3-oss/env-nextjs': 0.13.8
  '@tabler/icons-react': 3.34.1
  '@tanstack/react-query': 5.85.6
  '@tanstack/react-query-devtools': 5.85.6
  '@tiptap/extension-link': 3.3.0
  '@tiptap/react': 3.3.0
  '@tiptap/starter-kit': 3.3.0
  '@trpc/client': 11.5.0
  '@trpc/react-query': 11.5.0
  '@trpc/server': 11.5.0
  '@types/node': 24.3.0
  '@types/react': 19.1.12
  '@types/react-dom': 19.1.9
  '@types/uuid': 10.0.0
  '@vercel/analytics': 1.5.0
  '@vercel/speed-insights': 1.2.0
  dayjs: 1.11.18
  embla-carousel-react: 8.6.0
  eslint: 9.34.0
  inngest: 3.40.1
  next: 15.5.2
  prettier: 3.6.2
  react: 19.1.1
  react-dom: 19.1.1
  recharts: 2.15.1
  superjson: 2.2.2
  postcss: 8.5.3
  postcss-preset-mantine: 1.17.0
  postcss-simple-vars: 7.0.1
  typescript-eslint: 8.39.0
  typescript: 5.9.2
  uuid: 11.1.0
  zod: 4.1.5
