import { v4 as uuidv4 } from "uuid";
export const electionCreationBase = {
  id: uuidv4(),
  name: "",
  about: "",
  electionIDName: "",
  ongoing: false,
  partylists: [
    {
      id: uuidv4(),
      title: "Independent",
      acronym: "IND",
    },
  ],
  positions: [],
  candidates: [],
  createdAt: new Date(),
  updatedAt: new Date(),
};

import {
  HomeIcon,
  UserCircleIcon,
  FlagIcon,
  UserIcon,
  CheckCircleIcon,
  CogIcon,
} from "@heroicons/react/outline";
import {
  HomeIcon as HomeIconSolid,
  UserCircleIcon as UserCircleIconSolid,
  FlagIcon as FlagIconSolid,
  UserIcon as UserIconSolid,
  CheckCircleIcon as CheckCircleIconSolid,
  CogIcon as CogIconSolid,
} from "@heroicons/react/solid";

export const dashboardSidebar = [
  {
    id: 1,
    name: "Overview",
    icon: <HomeIcon />,
    iconSelect: <HomeIconSolid />,
  },
  {
    id: 2,
    name: "Position",
    icon: <UserCircleIcon />,
    iconSelect: <UserCircleIconSolid />,
  },
  {
    id: 3,
    name: "Partylist",
    icon: <FlagIcon />,
    iconSelect: <FlagIconSolid />,
  },
  {
    id: 4,
    name: "Candidate",
    icon: <UserIcon />,
    iconSelect: <UserIconSolid />,
  },
  {
    id: 5,
    name: "Voter",
    icon: <CheckCircleIcon />,
    iconSelect: <CheckCircleIconSolid />,
  },
  {
    id: 6,
    name: "Settings",
    icon: <CogIcon />,
    iconSelect: <CogIconSolid />,
  },
];

export const elections = [
  {
    id: 1,
    name: "CSSO Election 2022",
    about:
      "COMPUTER SCIENCE STUDENT ORGANIZATION (CSSO) is legally recognized organization that serves Computer Science students, to the extent possible by law, emphasizes participation of students from groups with low rates of eligibility to four year institutions. CSSO Offers a pipeline of extra-curricular services from first year to fourth year students to increase the number of students who graduated with Bachelor of Science in Computer Science. The CSSO was established to assist, advice and develop BSCS students to achieve optimum academic and technical performance in chosen field of specialty.",
    electionIDName: "CSSOElection2022",
    ongoing: true,
    positions: [
      {
        id: 0,
        title: "President",
        undecidedVotingCount: 0,
      },
      {
        id: 1,
        title: "VP for Internal Affairs",
        undecidedVotingCount: 0,
      },
      {
        id: 2,
        title: "VP for External Affairs",
        undecidedVotingCount: 0,
      },
      {
        id: 3,
        title: "Secretary",
        undecidedVotingCount: 0,
      },
      {
        id: 4,
        title: "Treasurer",
        undecidedVotingCount: 0,
      },
      {
        id: 5,
        title: "Auditor",
        undecidedVotingCount: 0,
      },
      {
        id: 6,
        title: "Business Manager",
        undecidedVotingCount: 0,
      },
      {
        id: 7,
        title: "Public Relation Officer",
        undecidedVotingCount: 0,
      },
    ],

    partylists: [
      {
        id: 0,
        title: "Independent",
        acronym: "IND",
      },
      {
        id: 1,
        title: "Wisely Party",
        acronym: "WP",
        about: "",
      },
      {
        id: 2,
        title: "Party Party",
        acronym: "PP",
        about: "",
      },
    ],
  },
];

export const candidates = [
  {
    id: 0,
    firstName: "Rey Anthony",
    middleName: "M",
    lastName: "De Luna",
    img: "https://github.com/COSC70A-Group1/eboto-mo/blob/main/src/assets/imgs/election/candidates/WP/0%20-%20President%20-%20De%20Luna.png?raw=true",
    position: elections[0].positions[0],
    partylist: elections[0].partylists[1],
    votingCount: 0,
    significantAchievements: [
      "With honors during Senior High School years",
      "Among top students of Computer Science",
    ],
    leadershipAchievements: [
      "Cadet officer in JHS",
      "SSG committee in SHS",
      "STEM Club Representative",
      "Class Representative BSCS 1-2 2020-2021",
      "Public Relation Officer of CSSO 2021-2022",
    ],
    question: {
      question:
        "What are your advocacies that will help your fellow Computer Science students in this time of pandemic?",
      answer: [
        "COVID-19 lockdowns and school closures have a devastating impact on student's health, well-being, and learning. All students don't have the same privilege, many are still using data connection on attending classes and submitting their activities. They are struggling on to where they are going to get the money for them to avail some data so that they can survive the semester. As a solution to this, I will continue the donation drive of the former officers. The donation drive aims to give free data connections to the computer science students, but before getting the freebie the students will be needing to pass some requirements for the officer to sort out the students that are really in need. The funds of the donation drive will come from activities such as e-tournament and so on.",
        "As for some students, connection is not their problem but the lack of discussion in some lessons. This problem leads to the students having difficulty in answering some of their activities, and the worst case is that they will not be able to build a good foundation for the post-requisite subjects since computer science subjects are linked to each other. And I am presenting the “Aid Tutorial Class” to solve this problem, the Aid Tutorial Class will be led by the officers and some students with a higher understanding on a particular subject. The Aid Class is not compulsory, it is for some students that have a free-time in their schedule, the said class will also be recorded so that the students that want to have more understanding but can't attend the class can still have the chance to learn. In addition to the Aid Class, I am also thinking on having a e-Library that is only exclusive to computer science students. The library will contain different lectures and practice activities, the collection of lectures and activities will be covering the lessons from first year level up to the fourth year.",
        "As a future leader, I will always listen to the student's voice and concerns. By hearing and aiding student's side, it will not just benefit them but it will also help my growth as a leader.",
        "What would be your plans and your platforms since there are news about the implementation of limited face-to-face classes that will ensure the safety of your fellow Computer Science students?",
        "In the age of coronavirus disease 2019, returning to school has taken on a new meaning and a new set of concerns for parents and other caregivers. In the middle of the COVID-19 pandemic, schools must now balance the educational, social, and emotional requirements of their students and staff along with the health and safety measurements. Multiple tools should be employed to keep everyone healthy. COVID-19 vaccines are available to everyone who qualifies, as well as universal masking, physical separation, handwashing, and remaining at home while sick. To make it work, everyone must do their part to ensure that students and staff remain physically fit and together at school.",
        "If the school permits and the face-to-face class will really happen, I am planning some ideas that can help computer science students to stay shielded on the virus. First, is on creating DIY with my co-officer a hand sanitizer stands for each classroom. The students will not be touching the sanitizers but they will step on some mechanism for them to sanitize before entering their respective room. Next, is having the Sanitize as you go policy in the computer laboratory. Since we are sharing the same computer laboratory with other students, we must sanitize equipment that we use to avoid contaminating the hardware. Last, is having a friendly competition with the section in every year on who can keep their respective classrooms clean and sanitize. They can be rewarded with some prizes that are beneficial during the pandemic like facemasks, alcohol, alcohol spray containers, and etc.",
        "Recently, #LetEarthBreathe trends on different social media platforms. As a future student leader, what would be your step to do to encourage your fellow Komsay students to save our nature?",
        "Due to the increased use of plastics, oil, and other fossil fuels, the destruction of the Earth is speeding up. We should all pay attention to qualified scientists and cooperate with them. Why aren't we changing with the climate? Our only home, the Earth, is fading. Let's join forces to save it. It doesn't matter how small or minor your acts and efforts are, it is the start of something big so it does still help.",
        "As a future leader and also a people of this world, I am proposing to the professors and the institution this one simple act. It can also serve as a requirement for us to graduate. The idea is to have a day at university where every student will plant atleast one tree sapling in areas that trees are really needed. It is not just a requirement for our completion, but it is also a big help to the young generation to see the beauty of our home. Whatever our goal in life, let us not forget that we are living in the same world so let's work together to save our beautiful home.",
      ],
    },
  },
  {
    id: 1,
    firstName: "John Marco",
    middleName: "E",
    lastName: "Dacumos",
    img: "https://github.com/COSC70A-Group1/eboto-mo/blob/main/src/assets/imgs/election/candidates/WP/1%20-%20VPInternal%20-%20Dacumos.png?raw=true",
    position: elections[0].positions[1],
    partylist: elections[0].partylists[1],
    votingCount: 0,
    significantAchievements: [
      "HONOR STUDENT (Junior & Senior High School)",
      "Outstanding CS Student AY 2020-2021/2021-2022 (First Year)",
      "Top 7 Outstanding CS Student 1st Semester AY 2021-2022 (Second Year)",
    ],
    leadershipAchievements: [
      "Junior Highschool Clubs Officer (2015, 2016)",
      "Senior Highschool SSG Officer (2019)",
      "BSCS 1-5 Class Representative (2020-2021)",
      "CSSO Vice President for Documentation (2021-2022)",
    ],
    question: {
      question:
        "What are your advocacies that will help your fellow Computer Science students in this time of pandemic?",
      answer: [
        "COVID-19 lockdowns and school closures have a devastating impact on student's health, well-being, and learning. All students don't have the same privilege, many are still using data connection on attending classes and submitting their activities. They are struggling on to where they are going to get the money for them to avail some data so that they can survive the semester. As a solution to this, I will continue the donation drive of the former officers. The donation drive aims to give free data connections to the computer science students, but before getting the freebie the students will be needing to pass some requirements for the officer to sort out the students that are really in need. The funds of the donation drive will come from activities such as e-tournament and so on.",
        "As for some students, connection is not their problem but the lack of discussion in some lessons. This problem leads to the students having difficulty in answering some of their activities, and the worst case is that they will not be able to build a good foundation for the post-requisite subjects since computer science subjects are linked to each other. And I am presenting the “Aid Tutorial Class” to solve this problem, the Aid Tutorial Class will be led by the officers and some students with a higher understanding on a particular subject. The Aid Class is not compulsory, it is for some students that have a free-time in their schedule, the said class will also be recorded so that the students that want to have more understanding but can't attend the class can still have the chance to learn. In addition to the Aid Class, I am also thinking on having a e-Library that is only exclusive to computer science students. The library will contain different lectures and practice activities, the collection of lectures and activities will be covering the lessons from first year level up to the fourth year.",
        "As a future leader, I will always listen to the student's voice and concerns. By hearing and aiding student's side, it will not just benefit them but it will also help my growth as a leader.",
        "What would be your plans and your platforms since there are news about the implementation of limited face-to-face classes that will ensure the safety of your fellow Computer Science students?",
        "In the age of coronavirus disease 2019, returning to school has taken on a new meaning and a new set of concerns for parents and other caregivers. In the middle of the COVID-19 pandemic, schools must now balance the educational, social, and emotional requirements of their students and staff along with the health and safety measurements. Multiple tools should be employed to keep everyone healthy. COVID-19 vaccines are available to everyone who qualifies, as well as universal masking, physical separation, handwashing, and remaining at home while sick. To make it work, everyone must do their part to ensure that students and staff remain physically fit and together at school.",
        "If the school permits and the face-to-face class will really happen, I am planning some ideas that can help computer science students to stay shielded on the virus. First, is on creating DIY with my co-officer a hand sanitizer stands for each classroom. The students will not be touching the sanitizers but they will step on some mechanism for them to sanitize before entering their respective room. Next, is having the Sanitize as you go policy in the computer laboratory. Since we are sharing the same computer laboratory with other students, we must sanitize equipment that we use to avoid contaminating the hardware. Last, is having a friendly competition with the section in every year on who can keep their respective classrooms clean and sanitize. They can be rewarded with some prizes that are beneficial during the pandemic like facemasks, alcohol, alcohol spray containers, and etc.",
        "Recently, #LetEarthBreathe trends on different social media platforms. As a future student leader, what would be your step to do to encourage your fellow Komsay students to save our nature?",
        "Due to the increased use of plastics, oil, and other fossil fuels, the destruction of the Earth is speeding up. We should all pay attention to qualified scientists and cooperate with them. Why aren't we changing with the climate? Our only home, the Earth, is fading. Let's join forces to save it. It doesn't matter how small or minor your acts and efforts are, it is the start of something big so it does still help.",
        "As a future leader and also a people of this world, I am proposing to the professors and the institution this one simple act. It can also serve as a requirement for us to graduate. The idea is to have a day at university where every student will plant atleast one tree sapling in areas that trees are really needed. It is not just a requirement for our completion, but it is also a big help to the young generation to see the beauty of our home. Whatever our goal in life, let us not forget that we are living in the same world so let's work together to save our beautiful home.",
      ],
    },
  },
  {
    id: 2,
    firstName: "Harvy",
    middleName: "S",
    lastName: "Dela Cruz",
    img: "https://github.com/COSC70A-Group1/eboto-mo/blob/main/src/assets/imgs/election/candidates/WP/2%20-%20VPExternal%20-%20Dela%20Cruz.png?raw=true",
    position: elections[0].positions[2],
    partylist: elections[0].partylists[1],
    votingCount: 0,
    significantAchievements: [
      "Consistent Honor Student",
      "National Certificate III Holder for Visual Graphic Design",
      "Conduct Awardee in SHS",
    ],
    leadershipAchievements: [
      "STEM CLUB Vice President 2019 - 2020",
      "STEM CLUB President 2020 - 2021",
    ],
    question: {
      question:
        "What are your advocacies that will help your fellow Computer Science students in this time of pandemic?",
      answer: [
        "COVID-19 lockdowns and school closures have a devastating impact on student's health, well-being, and learning. All students don't have the same privilege, many are still using data connection on attending classes and submitting their activities. They are struggling on to where they are going to get the money for them to avail some data so that they can survive the semester. As a solution to this, I will continue the donation drive of the former officers. The donation drive aims to give free data connections to the computer science students, but before getting the freebie the students will be needing to pass some requirements for the officer to sort out the students that are really in need. The funds of the donation drive will come from activities such as e-tournament and so on.",
        "As for some students, connection is not their problem but the lack of discussion in some lessons. This problem leads to the students having difficulty in answering some of their activities, and the worst case is that they will not be able to build a good foundation for the post-requisite subjects since computer science subjects are linked to each other. And I am presenting the “Aid Tutorial Class” to solve this problem, the Aid Tutorial Class will be led by the officers and some students with a higher understanding on a particular subject. The Aid Class is not compulsory, it is for some students that have a free-time in their schedule, the said class will also be recorded so that the students that want to have more understanding but can't attend the class can still have the chance to learn. In addition to the Aid Class, I am also thinking on having a e-Library that is only exclusive to computer science students. The library will contain different lectures and practice activities, the collection of lectures and activities will be covering the lessons from first year level up to the fourth year.",
        "As a future leader, I will always listen to the student's voice and concerns. By hearing and aiding student's side, it will not just benefit them but it will also help my growth as a leader.",
        "What would be your plans and your platforms since there are news about the implementation of limited face-to-face classes that will ensure the safety of your fellow Computer Science students?",
        "In the age of coronavirus disease 2019, returning to school has taken on a new meaning and a new set of concerns for parents and other caregivers. In the middle of the COVID-19 pandemic, schools must now balance the educational, social, and emotional requirements of their students and staff along with the health and safety measurements. Multiple tools should be employed to keep everyone healthy. COVID-19 vaccines are available to everyone who qualifies, as well as universal masking, physical separation, handwashing, and remaining at home while sick. To make it work, everyone must do their part to ensure that students and staff remain physically fit and together at school.",
        "If the school permits and the face-to-face class will really happen, I am planning some ideas that can help computer science students to stay shielded on the virus. First, is on creating DIY with my co-officer a hand sanitizer stands for each classroom. The students will not be touching the sanitizers but they will step on some mechanism for them to sanitize before entering their respective room. Next, is having the Sanitize as you go policy in the computer laboratory. Since we are sharing the same computer laboratory with other students, we must sanitize equipment that we use to avoid contaminating the hardware. Last, is having a friendly competition with the section in every year on who can keep their respective classrooms clean and sanitize. They can be rewarded with some prizes that are beneficial during the pandemic like facemasks, alcohol, alcohol spray containers, and etc.",
        "Recently, #LetEarthBreathe trends on different social media platforms. As a future student leader, what would be your step to do to encourage your fellow Komsay students to save our nature?",
        "Due to the increased use of plastics, oil, and other fossil fuels, the destruction of the Earth is speeding up. We should all pay attention to qualified scientists and cooperate with them. Why aren't we changing with the climate? Our only home, the Earth, is fading. Let's join forces to save it. It doesn't matter how small or minor your acts and efforts are, it is the start of something big so it does still help.",
        "As a future leader and also a people of this world, I am proposing to the professors and the institution this one simple act. It can also serve as a requirement for us to graduate. The idea is to have a day at university where every student will plant atleast one tree sapling in areas that trees are really needed. It is not just a requirement for our completion, but it is also a big help to the young generation to see the beauty of our home. Whatever our goal in life, let us not forget that we are living in the same world so let's work together to save our beautiful home.",
      ],
    },
  },
  {
    id: 3,
    firstName: "Spencer",
    middleName: "A",
    lastName: "Mandid",
    img: "https://github.com/COSC70A-Group1/eboto-mo/blob/main/src/assets/imgs/election/candidates/WP/3%20-%20Secretary%20-%20Mandid.png?raw=true",
    position: elections[0].positions[3],
    partylist: elections[0].partylists[1],
    votingCount: 0,
    significantAchievements: [
      "7th Honorable Mention Impromptu Speech in Oral Communication in Notre Dame of Trece Martirez",
      "Top 8 CSSO's 3rd Gawad Durungawan in CvSU - Cavite State University",
      "G11 - Science, Technology, Engineering and Mathematics With Honors in Notre Dame of Trece Martirez",
    ],
    leadershipAchievements: ["BSCS 1-3 Class Representative 2021-2022"],
    question: {
      question:
        "What are your advocacies that will help your fellow Computer Science students in this time of pandemic?",
      answer: [
        "COVID-19 lockdowns and school closures have a devastating impact on student's health, well-being, and learning. All students don't have the same privilege, many are still using data connection on attending classes and submitting their activities. They are struggling on to where they are going to get the money for them to avail some data so that they can survive the semester. As a solution to this, I will continue the donation drive of the former officers. The donation drive aims to give free data connections to the computer science students, but before getting the freebie the students will be needing to pass some requirements for the officer to sort out the students that are really in need. The funds of the donation drive will come from activities such as e-tournament and so on.",
        "As for some students, connection is not their problem but the lack of discussion in some lessons. This problem leads to the students having difficulty in answering some of their activities, and the worst case is that they will not be able to build a good foundation for the post-requisite subjects since computer science subjects are linked to each other. And I am presenting the “Aid Tutorial Class” to solve this problem, the Aid Tutorial Class will be led by the officers and some students with a higher understanding on a particular subject. The Aid Class is not compulsory, it is for some students that have a free-time in their schedule, the said class will also be recorded so that the students that want to have more understanding but can't attend the class can still have the chance to learn. In addition to the Aid Class, I am also thinking on having a e-Library that is only exclusive to computer science students. The library will contain different lectures and practice activities, the collection of lectures and activities will be covering the lessons from first year level up to the fourth year.",
        "As a future leader, I will always listen to the student's voice and concerns. By hearing and aiding student's side, it will not just benefit them but it will also help my growth as a leader.",
        "What would be your plans and your platforms since there are news about the implementation of limited face-to-face classes that will ensure the safety of your fellow Computer Science students?",
        "In the age of coronavirus disease 2019, returning to school has taken on a new meaning and a new set of concerns for parents and other caregivers. In the middle of the COVID-19 pandemic, schools must now balance the educational, social, and emotional requirements of their students and staff along with the health and safety measurements. Multiple tools should be employed to keep everyone healthy. COVID-19 vaccines are available to everyone who qualifies, as well as universal masking, physical separation, handwashing, and remaining at home while sick. To make it work, everyone must do their part to ensure that students and staff remain physically fit and together at school.",
        "If the school permits and the face-to-face class will really happen, I am planning some ideas that can help computer science students to stay shielded on the virus. First, is on creating DIY with my co-officer a hand sanitizer stands for each classroom. The students will not be touching the sanitizers but they will step on some mechanism for them to sanitize before entering their respective room. Next, is having the Sanitize as you go policy in the computer laboratory. Since we are sharing the same computer laboratory with other students, we must sanitize equipment that we use to avoid contaminating the hardware. Last, is having a friendly competition with the section in every year on who can keep their respective classrooms clean and sanitize. They can be rewarded with some prizes that are beneficial during the pandemic like facemasks, alcohol, alcohol spray containers, and etc.",
        "Recently, #LetEarthBreathe trends on different social media platforms. As a future student leader, what would be your step to do to encourage your fellow Komsay students to save our nature?",
        "Due to the increased use of plastics, oil, and other fossil fuels, the destruction of the Earth is speeding up. We should all pay attention to qualified scientists and cooperate with them. Why aren't we changing with the climate? Our only home, the Earth, is fading. Let's join forces to save it. It doesn't matter how small or minor your acts and efforts are, it is the start of something big so it does still help.",
        "As a future leader and also a people of this world, I am proposing to the professors and the institution this one simple act. It can also serve as a requirement for us to graduate. The idea is to have a day at university where every student will plant atleast one tree sapling in areas that trees are really needed. It is not just a requirement for our completion, but it is also a big help to the young generation to see the beauty of our home. Whatever our goal in life, let us not forget that we are living in the same world so let's work together to save our beautiful home.",
      ],
    },
  },
  {
    id: 4,
    firstName: "Harvey",
    middleName: "A",
    lastName: "Equacion",
    img: "https://github.com/COSC70A-Group1/eboto-mo/blob/main/src/assets/imgs/election/candidates/WP/4%20-%20Treasurer%20-%20Equacion.png?raw=true",
    position: elections[0].positions[4],
    partylist: elections[0].partylists[1],
    votingCount: 0,
    significantAchievements: ["With honors in Senior Highschool"],
    leadershipAchievements: ["BSCS 2-5 Class Representative 2021-2022"],
    question: {
      question:
        "What are your advocacies that will help your fellow Computer Science students in this time of pandemic?",
      answer: [
        "COVID-19 lockdowns and school closures have a devastating impact on student's health, well-being, and learning. All students don't have the same privilege, many are still using data connection on attending classes and submitting their activities. They are struggling on to where they are going to get the money for them to avail some data so that they can survive the semester. As a solution to this, I will continue the donation drive of the former officers. The donation drive aims to give free data connections to the computer science students, but before getting the freebie the students will be needing to pass some requirements for the officer to sort out the students that are really in need. The funds of the donation drive will come from activities such as e-tournament and so on.",
        "As for some students, connection is not their problem but the lack of discussion in some lessons. This problem leads to the students having difficulty in answering some of their activities, and the worst case is that they will not be able to build a good foundation for the post-requisite subjects since computer science subjects are linked to each other. And I am presenting the “Aid Tutorial Class” to solve this problem, the Aid Tutorial Class will be led by the officers and some students with a higher understanding on a particular subject. The Aid Class is not compulsory, it is for some students that have a free-time in their schedule, the said class will also be recorded so that the students that want to have more understanding but can't attend the class can still have the chance to learn. In addition to the Aid Class, I am also thinking on having a e-Library that is only exclusive to computer science students. The library will contain different lectures and practice activities, the collection of lectures and activities will be covering the lessons from first year level up to the fourth year.",
        "As a future leader, I will always listen to the student's voice and concerns. By hearing and aiding student's side, it will not just benefit them but it will also help my growth as a leader.",
        "What would be your plans and your platforms since there are news about the implementation of limited face-to-face classes that will ensure the safety of your fellow Computer Science students?",
        "In the age of coronavirus disease 2019, returning to school has taken on a new meaning and a new set of concerns for parents and other caregivers. In the middle of the COVID-19 pandemic, schools must now balance the educational, social, and emotional requirements of their students and staff along with the health and safety measurements. Multiple tools should be employed to keep everyone healthy. COVID-19 vaccines are available to everyone who qualifies, as well as universal masking, physical separation, handwashing, and remaining at home while sick. To make it work, everyone must do their part to ensure that students and staff remain physically fit and together at school.",
        "If the school permits and the face-to-face class will really happen, I am planning some ideas that can help computer science students to stay shielded on the virus. First, is on creating DIY with my co-officer a hand sanitizer stands for each classroom. The students will not be touching the sanitizers but they will step on some mechanism for them to sanitize before entering their respective room. Next, is having the Sanitize as you go policy in the computer laboratory. Since we are sharing the same computer laboratory with other students, we must sanitize equipment that we use to avoid contaminating the hardware. Last, is having a friendly competition with the section in every year on who can keep their respective classrooms clean and sanitize. They can be rewarded with some prizes that are beneficial during the pandemic like facemasks, alcohol, alcohol spray containers, and etc.",
        "Recently, #LetEarthBreathe trends on different social media platforms. As a future student leader, what would be your step to do to encourage your fellow Komsay students to save our nature?",
        "Due to the increased use of plastics, oil, and other fossil fuels, the destruction of the Earth is speeding up. We should all pay attention to qualified scientists and cooperate with them. Why aren't we changing with the climate? Our only home, the Earth, is fading. Let's join forces to save it. It doesn't matter how small or minor your acts and efforts are, it is the start of something big so it does still help.",
        "As a future leader and also a people of this world, I am proposing to the professors and the institution this one simple act. It can also serve as a requirement for us to graduate. The idea is to have a day at university where every student will plant atleast one tree sapling in areas that trees are really needed. It is not just a requirement for our completion, but it is also a big help to the young generation to see the beauty of our home. Whatever our goal in life, let us not forget that we are living in the same world so let's work together to save our beautiful home.",
      ],
    },
  },
  {
    id: 5,
    firstName: "Trissian",
    middleName: "",
    lastName: "Urate",
    img: "https://github.com/COSC70A-Group1/eboto-mo/blob/main/src/assets/imgs/election/candidates/WP/5%20-%20Auditor%20-%20Urate.png?raw=true",
    position: elections[0].positions[5],
    partylist: elections[0].partylists[1],
    votingCount: 0,
    significantAchievements: [
      "With Honors (Junior High School)",
      "With Honors (Grade 11)",
      "With High Honors (Grade 12)",
      "Top 2 Gawad Durungawan 1st Semester AY 2021-2022",
    ],
    leadershipAchievements: ["N/A"],
    question: {
      question:
        "What are your advocacies that will help your fellow Computer Science students in this time of pandemic?",
      answer: [
        "COVID-19 lockdowns and school closures have a devastating impact on student's health, well-being, and learning. All students don't have the same privilege, many are still using data connection on attending classes and submitting their activities. They are struggling on to where they are going to get the money for them to avail some data so that they can survive the semester. As a solution to this, I will continue the donation drive of the former officers. The donation drive aims to give free data connections to the computer science students, but before getting the freebie the students will be needing to pass some requirements for the officer to sort out the students that are really in need. The funds of the donation drive will come from activities such as e-tournament and so on.",
        "As for some students, connection is not their problem but the lack of discussion in some lessons. This problem leads to the students having difficulty in answering some of their activities, and the worst case is that they will not be able to build a good foundation for the post-requisite subjects since computer science subjects are linked to each other. And I am presenting the “Aid Tutorial Class” to solve this problem, the Aid Tutorial Class will be led by the officers and some students with a higher understanding on a particular subject. The Aid Class is not compulsory, it is for some students that have a free-time in their schedule, the said class will also be recorded so that the students that want to have more understanding but can't attend the class can still have the chance to learn. In addition to the Aid Class, I am also thinking on having a e-Library that is only exclusive to computer science students. The library will contain different lectures and practice activities, the collection of lectures and activities will be covering the lessons from first year level up to the fourth year.",
        "As a future leader, I will always listen to the student's voice and concerns. By hearing and aiding student's side, it will not just benefit them but it will also help my growth as a leader.",
        "What would be your plans and your platforms since there are news about the implementation of limited face-to-face classes that will ensure the safety of your fellow Computer Science students?",
        "In the age of coronavirus disease 2019, returning to school has taken on a new meaning and a new set of concerns for parents and other caregivers. In the middle of the COVID-19 pandemic, schools must now balance the educational, social, and emotional requirements of their students and staff along with the health and safety measurements. Multiple tools should be employed to keep everyone healthy. COVID-19 vaccines are available to everyone who qualifies, as well as universal masking, physical separation, handwashing, and remaining at home while sick. To make it work, everyone must do their part to ensure that students and staff remain physically fit and together at school.",
        "If the school permits and the face-to-face class will really happen, I am planning some ideas that can help computer science students to stay shielded on the virus. First, is on creating DIY with my co-officer a hand sanitizer stands for each classroom. The students will not be touching the sanitizers but they will step on some mechanism for them to sanitize before entering their respective room. Next, is having the Sanitize as you go policy in the computer laboratory. Since we are sharing the same computer laboratory with other students, we must sanitize equipment that we use to avoid contaminating the hardware. Last, is having a friendly competition with the section in every year on who can keep their respective classrooms clean and sanitize. They can be rewarded with some prizes that are beneficial during the pandemic like facemasks, alcohol, alcohol spray containers, and etc.",
        "Recently, #LetEarthBreathe trends on different social media platforms. As a future student leader, what would be your step to do to encourage your fellow Komsay students to save our nature?",
        "Due to the increased use of plastics, oil, and other fossil fuels, the destruction of the Earth is speeding up. We should all pay attention to qualified scientists and cooperate with them. Why aren't we changing with the climate? Our only home, the Earth, is fading. Let's join forces to save it. It doesn't matter how small or minor your acts and efforts are, it is the start of something big so it does still help.",
        "As a future leader and also a people of this world, I am proposing to the professors and the institution this one simple act. It can also serve as a requirement for us to graduate. The idea is to have a day at university where every student will plant atleast one tree sapling in areas that trees are really needed. It is not just a requirement for our completion, but it is also a big help to the young generation to see the beauty of our home. Whatever our goal in life, let us not forget that we are living in the same world so let's work together to save our beautiful home.",
      ],
    },
  },
  {
    id: 6,
    firstName: "Jaquelyn",
    middleName: "N",
    lastName: "Dela Cruz",
    img: "https://github.com/COSC70A-Group1/eboto-mo/blob/main/src/assets/imgs/election/candidates/WP/6%20-%20BusinessManager%20-%20Dela%20Cruz.png?raw=true",
    position: elections[0].positions[6],
    partylist: elections[0].partylists[1],
    votingCount: 0,
    significantAchievements: [
      "Academic Excellence With Honors both Junior High School and Senior High School Years",
      "Award for Outstanding Performance in Specific Discipline: Science",
      "2nd Place Division Festival of Talents in Science 2019 - Robotics Competition Sumobot",
      "4th Place Science Innovation Expo 2019 - Individual Category",
    ],
    leadershipAchievements: ["Supreme Student Government Officer"],
    question: {
      question:
        "What are your advocacies that will help your fellow Computer Science students in this time of pandemic?",
      answer: [
        "COVID-19 lockdowns and school closures have a devastating impact on student's health, well-being, and learning. All students don't have the same privilege, many are still using data connection on attending classes and submitting their activities. They are struggling on to where they are going to get the money for them to avail some data so that they can survive the semester. As a solution to this, I will continue the donation drive of the former officers. The donation drive aims to give free data connections to the computer science students, but before getting the freebie the students will be needing to pass some requirements for the officer to sort out the students that are really in need. The funds of the donation drive will come from activities such as e-tournament and so on.",
        "As for some students, connection is not their problem but the lack of discussion in some lessons. This problem leads to the students having difficulty in answering some of their activities, and the worst case is that they will not be able to build a good foundation for the post-requisite subjects since computer science subjects are linked to each other. And I am presenting the “Aid Tutorial Class” to solve this problem, the Aid Tutorial Class will be led by the officers and some students with a higher understanding on a particular subject. The Aid Class is not compulsory, it is for some students that have a free-time in their schedule, the said class will also be recorded so that the students that want to have more understanding but can't attend the class can still have the chance to learn. In addition to the Aid Class, I am also thinking on having a e-Library that is only exclusive to computer science students. The library will contain different lectures and practice activities, the collection of lectures and activities will be covering the lessons from first year level up to the fourth year.",
        "As a future leader, I will always listen to the student's voice and concerns. By hearing and aiding student's side, it will not just benefit them but it will also help my growth as a leader.",
        "What would be your plans and your platforms since there are news about the implementation of limited face-to-face classes that will ensure the safety of your fellow Computer Science students?",
        "In the age of coronavirus disease 2019, returning to school has taken on a new meaning and a new set of concerns for parents and other caregivers. In the middle of the COVID-19 pandemic, schools must now balance the educational, social, and emotional requirements of their students and staff along with the health and safety measurements. Multiple tools should be employed to keep everyone healthy. COVID-19 vaccines are available to everyone who qualifies, as well as universal masking, physical separation, handwashing, and remaining at home while sick. To make it work, everyone must do their part to ensure that students and staff remain physically fit and together at school.",
        "If the school permits and the face-to-face class will really happen, I am planning some ideas that can help computer science students to stay shielded on the virus. First, is on creating DIY with my co-officer a hand sanitizer stands for each classroom. The students will not be touching the sanitizers but they will step on some mechanism for them to sanitize before entering their respective room. Next, is having the Sanitize as you go policy in the computer laboratory. Since we are sharing the same computer laboratory with other students, we must sanitize equipment that we use to avoid contaminating the hardware. Last, is having a friendly competition with the section in every year on who can keep their respective classrooms clean and sanitize. They can be rewarded with some prizes that are beneficial during the pandemic like facemasks, alcohol, alcohol spray containers, and etc.",
        "Recently, #LetEarthBreathe trends on different social media platforms. As a future student leader, what would be your step to do to encourage your fellow Komsay students to save our nature?",
        "Due to the increased use of plastics, oil, and other fossil fuels, the destruction of the Earth is speeding up. We should all pay attention to qualified scientists and cooperate with them. Why aren't we changing with the climate? Our only home, the Earth, is fading. Let's join forces to save it. It doesn't matter how small or minor your acts and efforts are, it is the start of something big so it does still help.",
        "As a future leader and also a people of this world, I am proposing to the professors and the institution this one simple act. It can also serve as a requirement for us to graduate. The idea is to have a day at university where every student will plant atleast one tree sapling in areas that trees are really needed. It is not just a requirement for our completion, but it is also a big help to the young generation to see the beauty of our home. Whatever our goal in life, let us not forget that we are living in the same world so let's work together to save our beautiful home.",
      ],
    },
  },
  {
    id: 7,
    firstName: "Aaron Joshua",
    middleName: "G",
    lastName: "Espinosa",
    img: "https://github.com/COSC70A-Group1/eboto-mo/blob/main/src/assets/imgs/election/candidates/WP/7%20-%20PublicRelationOfficer%20-%20Espinosa.png?raw=true",
    position: elections[0].positions[7],
    partylist: elections[0].partylists[1],
    votingCount: 0,
    significantAchievements: ["Consistent Honor Student SHS"],
    leadershipAchievements: [
      "BSCS 1-3 Class Representative 2020-2021",
      "ROTC Platoon Leader (Whisky) 2020-2021",
      "CSSO VP External 2021-2022",
    ],
    question: {
      question:
        "What are your advocacies that will help your fellow Computer Science students in this time of pandemic?",
      answer: [
        "COVID-19 lockdowns and school closures have a devastating impact on student's health, well-being, and learning. All students don't have the same privilege, many are still using data connection on attending classes and submitting their activities. They are struggling on to where they are going to get the money for them to avail some data so that they can survive the semester. As a solution to this, I will continue the donation drive of the former officers. The donation drive aims to give free data connections to the computer science students, but before getting the freebie the students will be needing to pass some requirements for the officer to sort out the students that are really in need. The funds of the donation drive will come from activities such as e-tournament and so on.",
        "As for some students, connection is not their problem but the lack of discussion in some lessons. This problem leads to the students having difficulty in answering some of their activities, and the worst case is that they will not be able to build a good foundation for the post-requisite subjects since computer science subjects are linked to each other. And I am presenting the “Aid Tutorial Class” to solve this problem, the Aid Tutorial Class will be led by the officers and some students with a higher understanding on a particular subject. The Aid Class is not compulsory, it is for some students that have a free-time in their schedule, the said class will also be recorded so that the students that want to have more understanding but can't attend the class can still have the chance to learn. In addition to the Aid Class, I am also thinking on having a e-Library that is only exclusive to computer science students. The library will contain different lectures and practice activities, the collection of lectures and activities will be covering the lessons from first year level up to the fourth year.",
        "As a future leader, I will always listen to the student's voice and concerns. By hearing and aiding student's side, it will not just benefit them but it will also help my growth as a leader.",
        "What would be your plans and your platforms since there are news about the implementation of limited face-to-face classes that will ensure the safety of your fellow Computer Science students?",
        "In the age of coronavirus disease 2019, returning to school has taken on a new meaning and a new set of concerns for parents and other caregivers. In the middle of the COVID-19 pandemic, schools must now balance the educational, social, and emotional requirements of their students and staff along with the health and safety measurements. Multiple tools should be employed to keep everyone healthy. COVID-19 vaccines are available to everyone who qualifies, as well as universal masking, physical separation, handwashing, and remaining at home while sick. To make it work, everyone must do their part to ensure that students and staff remain physically fit and together at school.",
        "If the school permits and the face-to-face class will really happen, I am planning some ideas that can help computer science students to stay shielded on the virus. First, is on creating DIY with my co-officer a hand sanitizer stands for each classroom. The students will not be touching the sanitizers but they will step on some mechanism for them to sanitize before entering their respective room. Next, is having the Sanitize as you go policy in the computer laboratory. Since we are sharing the same computer laboratory with other students, we must sanitize equipment that we use to avoid contaminating the hardware. Last, is having a friendly competition with the section in every year on who can keep their respective classrooms clean and sanitize. They can be rewarded with some prizes that are beneficial during the pandemic like facemasks, alcohol, alcohol spray containers, and etc.",
        "Recently, #LetEarthBreathe trends on different social media platforms. As a future student leader, what would be your step to do to encourage your fellow Komsay students to save our nature?",
        "Due to the increased use of plastics, oil, and other fossil fuels, the destruction of the Earth is speeding up. We should all pay attention to qualified scientists and cooperate with them. Why aren't we changing with the climate? Our only home, the Earth, is fading. Let's join forces to save it. It doesn't matter how small or minor your acts and efforts are, it is the start of something big so it does still help.",
        "As a future leader and also a people of this world, I am proposing to the professors and the institution this one simple act. It can also serve as a requirement for us to graduate. The idea is to have a day at university where every student will plant atleast one tree sapling in areas that trees are really needed. It is not just a requirement for our completion, but it is also a big help to the young generation to see the beauty of our home. Whatever our goal in life, let us not forget that we are living in the same world so let's work together to save our beautiful home.",
      ],
    },
  },
  {
    id: 8,
    firstName: "Brice Brine",
    middleName: "Silagan",
    lastName: "Suazo",
    img: "https://github.com/COSC70A-Group1/eboto-mo/blob/main/src/assets/imgs/election/candidates/PP/0%20-%20President%20-%20Suazo.png?raw=true",
    position: elections[0].positions[0],
    partylist: elections[0].partylists[2],
    votingCount: 0,
    significantAchievements: [
      "With honors during Senior High School years",
      "Among top students of Computer Science",
    ],
    leadershipAchievements: [
      "Cadet officer in JHS",
      "SSG committee in SHS",
      "STEM Club Representative",
      "Class Representative BSCS 1-2 2020-2021",
      "Public Relation Officer of CSSO 2021-2022",
    ],
    question: {
      question:
        "What are your advocacies that will help your fellow Computer Science students in this time of pandemic?",
      answer: [
        "COVID-19 lockdowns and school closures have a devastating impact on student's health, well-being, and learning. All students don't have the same privilege, many are still using data connection on attending classes and submitting their activities. They are struggling on to where they are going to get the money for them to avail some data so that they can survive the semester. As a solution to this, I will continue the donation drive of the former officers. The donation drive aims to give free data connections to the computer science students, but before getting the freebie the students will be needing to pass some requirements for the officer to sort out the students that are really in need. The funds of the donation drive will come from activities such as e-tournament and so on.",
        "As for some students, connection is not their problem but the lack of discussion in some lessons. This problem leads to the students having difficulty in answering some of their activities, and the worst case is that they will not be able to build a good foundation for the post-requisite subjects since computer science subjects are linked to each other. And I am presenting the “Aid Tutorial Class” to solve this problem, the Aid Tutorial Class will be led by the officers and some students with a higher understanding on a particular subject. The Aid Class is not compulsory, it is for some students that have a free-time in their schedule, the said class will also be recorded so that the students that want to have more understanding but can't attend the class can still have the chance to learn. In addition to the Aid Class, I am also thinking on having a e-Library that is only exclusive to computer science students. The library will contain different lectures and practice activities, the collection of lectures and activities will be covering the lessons from first year level up to the fourth year.",
        "As a future leader, I will always listen to the student's voice and concerns. By hearing and aiding student's side, it will not just benefit them but it will also help my growth as a leader.",
        "What would be your plans and your platforms since there are news about the implementation of limited face-to-face classes that will ensure the safety of your fellow Computer Science students?",
        "In the age of coronavirus disease 2019, returning to school has taken on a new meaning and a new set of concerns for parents and other caregivers. In the middle of the COVID-19 pandemic, schools must now balance the educational, social, and emotional requirements of their students and staff along with the health and safety measurements. Multiple tools should be employed to keep everyone healthy. COVID-19 vaccines are available to everyone who qualifies, as well as universal masking, physical separation, handwashing, and remaining at home while sick. To make it work, everyone must do their part to ensure that students and staff remain physically fit and together at school.",
        "If the school permits and the face-to-face class will really happen, I am planning some ideas that can help computer science students to stay shielded on the virus. First, is on creating DIY with my co-officer a hand sanitizer stands for each classroom. The students will not be touching the sanitizers but they will step on some mechanism for them to sanitize before entering their respective room. Next, is having the Sanitize as you go policy in the computer laboratory. Since we are sharing the same computer laboratory with other students, we must sanitize equipment that we use to avoid contaminating the hardware. Last, is having a friendly competition with the section in every year on who can keep their respective classrooms clean and sanitize. They can be rewarded with some prizes that are beneficial during the pandemic like facemasks, alcohol, alcohol spray containers, and etc.",
        "Recently, #LetEarthBreathe trends on different social media platforms. As a future student leader, what would be your step to do to encourage your fellow Komsay students to save our nature?",
        "Due to the increased use of plastics, oil, and other fossil fuels, the destruction of the Earth is speeding up. We should all pay attention to qualified scientists and cooperate with them. Why aren't we changing with the climate? Our only home, the Earth, is fading. Let's join forces to save it. It doesn't matter how small or minor your acts and efforts are, it is the start of something big so it does still help.",
        "As a future leader and also a people of this world, I am proposing to the professors and the institution this one simple act. It can also serve as a requirement for us to graduate. The idea is to have a day at university where every student will plant atleast one tree sapling in areas that trees are really needed. It is not just a requirement for our completion, but it is also a big help to the young generation to see the beauty of our home. Whatever our goal in life, let us not forget that we are living in the same world so let's work together to save our beautiful home.",
      ],
    },
  },
  {
    id: 9,
    firstName: "Lourielene",
    middleName: "F",
    lastName: "Baldomero",
    img: "https://github.com/COSC70A-Group1/eboto-mo/blob/main/src/assets/imgs/election/candidates/PP/1%20-%20VPInternal%20-%20Baldomero.png?raw=true",
    position: elections[0].positions[1],
    partylist: elections[0].partylists[2],
    votingCount: 0,
    significantAchievements: [
      "With honors during Senior High School years",
      "Among top students of Computer Science",
    ],
    leadershipAchievements: [
      "Cadet officer in JHS",
      "SSG committee in SHS",
      "STEM Club Representative",
      "Class Representative BSCS 1-2 2020-2021",
      "Public Relation Officer of CSSO 2021-2022",
    ],
    question: {
      question:
        "What are your advocacies that will help your fellow Computer Science students in this time of pandemic?",
      answer: [
        "COVID-19 lockdowns and school closures have a devastating impact on student's health, well-being, and learning. All students don't have the same privilege, many are still using data connection on attending classes and submitting their activities. They are struggling on to where they are going to get the money for them to avail some data so that they can survive the semester. As a solution to this, I will continue the donation drive of the former officers. The donation drive aims to give free data connections to the computer science students, but before getting the freebie the students will be needing to pass some requirements for the officer to sort out the students that are really in need. The funds of the donation drive will come from activities such as e-tournament and so on.",
        "As for some students, connection is not their problem but the lack of discussion in some lessons. This problem leads to the students having difficulty in answering some of their activities, and the worst case is that they will not be able to build a good foundation for the post-requisite subjects since computer science subjects are linked to each other. And I am presenting the “Aid Tutorial Class” to solve this problem, the Aid Tutorial Class will be led by the officers and some students with a higher understanding on a particular subject. The Aid Class is not compulsory, it is for some students that have a free-time in their schedule, the said class will also be recorded so that the students that want to have more understanding but can't attend the class can still have the chance to learn. In addition to the Aid Class, I am also thinking on having a e-Library that is only exclusive to computer science students. The library will contain different lectures and practice activities, the collection of lectures and activities will be covering the lessons from first year level up to the fourth year.",
        "As a future leader, I will always listen to the student's voice and concerns. By hearing and aiding student's side, it will not just benefit them but it will also help my growth as a leader.",
        "What would be your plans and your platforms since there are news about the implementation of limited face-to-face classes that will ensure the safety of your fellow Computer Science students?",
        "In the age of coronavirus disease 2019, returning to school has taken on a new meaning and a new set of concerns for parents and other caregivers. In the middle of the COVID-19 pandemic, schools must now balance the educational, social, and emotional requirements of their students and staff along with the health and safety measurements. Multiple tools should be employed to keep everyone healthy. COVID-19 vaccines are available to everyone who qualifies, as well as universal masking, physical separation, handwashing, and remaining at home while sick. To make it work, everyone must do their part to ensure that students and staff remain physically fit and together at school.",
        "If the school permits and the face-to-face class will really happen, I am planning some ideas that can help computer science students to stay shielded on the virus. First, is on creating DIY with my co-officer a hand sanitizer stands for each classroom. The students will not be touching the sanitizers but they will step on some mechanism for them to sanitize before entering their respective room. Next, is having the Sanitize as you go policy in the computer laboratory. Since we are sharing the same computer laboratory with other students, we must sanitize equipment that we use to avoid contaminating the hardware. Last, is having a friendly competition with the section in every year on who can keep their respective classrooms clean and sanitize. They can be rewarded with some prizes that are beneficial during the pandemic like facemasks, alcohol, alcohol spray containers, and etc.",
        "Recently, #LetEarthBreathe trends on different social media platforms. As a future student leader, what would be your step to do to encourage your fellow Komsay students to save our nature?",
        "Due to the increased use of plastics, oil, and other fossil fuels, the destruction of the Earth is speeding up. We should all pay attention to qualified scientists and cooperate with them. Why aren't we changing with the climate? Our only home, the Earth, is fading. Let's join forces to save it. It doesn't matter how small or minor your acts and efforts are, it is the start of something big so it does still help.",
        "As a future leader and also a people of this world, I am proposing to the professors and the institution this one simple act. It can also serve as a requirement for us to graduate. The idea is to have a day at university where every student will plant atleast one tree sapling in areas that trees are really needed. It is not just a requirement for our completion, but it is also a big help to the young generation to see the beauty of our home. Whatever our goal in life, let us not forget that we are living in the same world so let's work together to save our beautiful home.",
      ],
    },
  },
  {
    id: 10,
    firstName: "Merc Jan Rale",
    middleName: "P",
    lastName: "Belanizo",
    img: "https://github.com/COSC70A-Group1/eboto-mo/blob/main/src/assets/imgs/election/candidates/PP/2%20-%20VPExternal%20-%20Belanizo.png?raw=true",
    position: elections[0].positions[2],
    partylist: elections[0].partylists[2],
    votingCount: 0,
    significantAchievements: [
      "With honors during Senior High School years",
      "Among top students of Computer Science",
    ],
    leadershipAchievements: [
      "Cadet officer in JHS",
      "SSG committee in SHS",
      "STEM Club Representative",
      "Class Representative BSCS 1-2 2020-2021",
      "Public Relation Officer of CSSO 2021-2022",
    ],
    question: {
      question:
        "What are your advocacies that will help your fellow Computer Science students in this time of pandemic?",
      answer: [
        "COVID-19 lockdowns and school closures have a devastating impact on student's health, well-being, and learning. All students don't have the same privilege, many are still using data connection on attending classes and submitting their activities. They are struggling on to where they are going to get the money for them to avail some data so that they can survive the semester. As a solution to this, I will continue the donation drive of the former officers. The donation drive aims to give free data connections to the computer science students, but before getting the freebie the students will be needing to pass some requirements for the officer to sort out the students that are really in need. The funds of the donation drive will come from activities such as e-tournament and so on.",
        "As for some students, connection is not their problem but the lack of discussion in some lessons. This problem leads to the students having difficulty in answering some of their activities, and the worst case is that they will not be able to build a good foundation for the post-requisite subjects since computer science subjects are linked to each other. And I am presenting the “Aid Tutorial Class” to solve this problem, the Aid Tutorial Class will be led by the officers and some students with a higher understanding on a particular subject. The Aid Class is not compulsory, it is for some students that have a free-time in their schedule, the said class will also be recorded so that the students that want to have more understanding but can't attend the class can still have the chance to learn. In addition to the Aid Class, I am also thinking on having a e-Library that is only exclusive to computer science students. The library will contain different lectures and practice activities, the collection of lectures and activities will be covering the lessons from first year level up to the fourth year.",
        "As a future leader, I will always listen to the student's voice and concerns. By hearing and aiding student's side, it will not just benefit them but it will also help my growth as a leader.",
        "What would be your plans and your platforms since there are news about the implementation of limited face-to-face classes that will ensure the safety of your fellow Computer Science students?",
        "In the age of coronavirus disease 2019, returning to school has taken on a new meaning and a new set of concerns for parents and other caregivers. In the middle of the COVID-19 pandemic, schools must now balance the educational, social, and emotional requirements of their students and staff along with the health and safety measurements. Multiple tools should be employed to keep everyone healthy. COVID-19 vaccines are available to everyone who qualifies, as well as universal masking, physical separation, handwashing, and remaining at home while sick. To make it work, everyone must do their part to ensure that students and staff remain physically fit and together at school.",
        "If the school permits and the face-to-face class will really happen, I am planning some ideas that can help computer science students to stay shielded on the virus. First, is on creating DIY with my co-officer a hand sanitizer stands for each classroom. The students will not be touching the sanitizers but they will step on some mechanism for them to sanitize before entering their respective room. Next, is having the Sanitize as you go policy in the computer laboratory. Since we are sharing the same computer laboratory with other students, we must sanitize equipment that we use to avoid contaminating the hardware. Last, is having a friendly competition with the section in every year on who can keep their respective classrooms clean and sanitize. They can be rewarded with some prizes that are beneficial during the pandemic like facemasks, alcohol, alcohol spray containers, and etc.",
        "Recently, #LetEarthBreathe trends on different social media platforms. As a future student leader, what would be your step to do to encourage your fellow Komsay students to save our nature?",
        "Due to the increased use of plastics, oil, and other fossil fuels, the destruction of the Earth is speeding up. We should all pay attention to qualified scientists and cooperate with them. Why aren't we changing with the climate? Our only home, the Earth, is fading. Let's join forces to save it. It doesn't matter how small or minor your acts and efforts are, it is the start of something big so it does still help.",
        "As a future leader and also a people of this world, I am proposing to the professors and the institution this one simple act. It can also serve as a requirement for us to graduate. The idea is to have a day at university where every student will plant atleast one tree sapling in areas that trees are really needed. It is not just a requirement for our completion, but it is also a big help to the young generation to see the beauty of our home. Whatever our goal in life, let us not forget that we are living in the same world so let's work together to save our beautiful home.",
      ],
    },
  },
  {
    id: 11,
    firstName: "Alex Kal-El",
    middleName: "A",
    lastName: "Buenviaje",
    img: "https://github.com/COSC70A-Group1/eboto-mo/blob/main/src/assets/imgs/election/candidates/PP/3%20-%20Secretary%20-%20Buenviaje.png?raw=true",
    position: elections[0].positions[3],
    partylist: elections[0].partylists[2],
    votingCount: 0,
    significantAchievements: [
      "With honors during Senior High School years",
      "Among top students of Computer Science",
    ],
    leadershipAchievements: [
      "Cadet officer in JHS",
      "SSG committee in SHS",
      "STEM Club Representative",
      "Class Representative BSCS 1-2 2020-2021",
      "Public Relation Officer of CSSO 2021-2022",
    ],
    question: {
      question:
        "What are your advocacies that will help your fellow Computer Science students in this time of pandemic?",
      answer: [
        "COVID-19 lockdowns and school closures have a devastating impact on student's health, well-being, and learning. All students don't have the same privilege, many are still using data connection on attending classes and submitting their activities. They are struggling on to where they are going to get the money for them to avail some data so that they can survive the semester. As a solution to this, I will continue the donation drive of the former officers. The donation drive aims to give free data connections to the computer science students, but before getting the freebie the students will be needing to pass some requirements for the officer to sort out the students that are really in need. The funds of the donation drive will come from activities such as e-tournament and so on.",
        "As for some students, connection is not their problem but the lack of discussion in some lessons. This problem leads to the students having difficulty in answering some of their activities, and the worst case is that they will not be able to build a good foundation for the post-requisite subjects since computer science subjects are linked to each other. And I am presenting the “Aid Tutorial Class” to solve this problem, the Aid Tutorial Class will be led by the officers and some students with a higher understanding on a particular subject. The Aid Class is not compulsory, it is for some students that have a free-time in their schedule, the said class will also be recorded so that the students that want to have more understanding but can't attend the class can still have the chance to learn. In addition to the Aid Class, I am also thinking on having a e-Library that is only exclusive to computer science students. The library will contain different lectures and practice activities, the collection of lectures and activities will be covering the lessons from first year level up to the fourth year.",
        "As a future leader, I will always listen to the student's voice and concerns. By hearing and aiding student's side, it will not just benefit them but it will also help my growth as a leader.",
        "What would be your plans and your platforms since there are news about the implementation of limited face-to-face classes that will ensure the safety of your fellow Computer Science students?",
        "In the age of coronavirus disease 2019, returning to school has taken on a new meaning and a new set of concerns for parents and other caregivers. In the middle of the COVID-19 pandemic, schools must now balance the educational, social, and emotional requirements of their students and staff along with the health and safety measurements. Multiple tools should be employed to keep everyone healthy. COVID-19 vaccines are available to everyone who qualifies, as well as universal masking, physical separation, handwashing, and remaining at home while sick. To make it work, everyone must do their part to ensure that students and staff remain physically fit and together at school.",
        "If the school permits and the face-to-face class will really happen, I am planning some ideas that can help computer science students to stay shielded on the virus. First, is on creating DIY with my co-officer a hand sanitizer stands for each classroom. The students will not be touching the sanitizers but they will step on some mechanism for them to sanitize before entering their respective room. Next, is having the Sanitize as you go policy in the computer laboratory. Since we are sharing the same computer laboratory with other students, we must sanitize equipment that we use to avoid contaminating the hardware. Last, is having a friendly competition with the section in every year on who can keep their respective classrooms clean and sanitize. They can be rewarded with some prizes that are beneficial during the pandemic like facemasks, alcohol, alcohol spray containers, and etc.",
        "Recently, #LetEarthBreathe trends on different social media platforms. As a future student leader, what would be your step to do to encourage your fellow Komsay students to save our nature?",
        "Due to the increased use of plastics, oil, and other fossil fuels, the destruction of the Earth is speeding up. We should all pay attention to qualified scientists and cooperate with them. Why aren't we changing with the climate? Our only home, the Earth, is fading. Let's join forces to save it. It doesn't matter how small or minor your acts and efforts are, it is the start of something big so it does still help.",
        "As a future leader and also a people of this world, I am proposing to the professors and the institution this one simple act. It can also serve as a requirement for us to graduate. The idea is to have a day at university where every student will plant atleast one tree sapling in areas that trees are really needed. It is not just a requirement for our completion, but it is also a big help to the young generation to see the beauty of our home. Whatever our goal in life, let us not forget that we are living in the same world so let's work together to save our beautiful home.",
      ],
    },
  },
  {
    id: 12,
    firstName: "John Lowell",
    middleName: "",
    lastName: "Mercado",
    img: "https://github.com/COSC70A-Group1/eboto-mo/blob/main/src/assets/imgs/election/candidates/PP/4%20-%20Treasurer%20-%20Mercado.png?raw=true",
    position: elections[0].positions[4],
    partylist: elections[0].partylists[2],
    votingCount: 0,
    significantAchievements: [
      "With honors during Senior High School years",
      "Among top students of Computer Science",
    ],
    leadershipAchievements: [
      "Cadet officer in JHS",
      "SSG committee in SHS",
      "STEM Club Representative",
      "Class Representative BSCS 1-2 2020-2021",
      "Public Relation Officer of CSSO 2021-2022",
    ],
    question: {
      question:
        "What are your advocacies that will help your fellow Computer Science students in this time of pandemic?",
      answer: [
        "COVID-19 lockdowns and school closures have a devastating impact on student's health, well-being, and learning. All students don't have the same privilege, many are still using data connection on attending classes and submitting their activities. They are struggling on to where they are going to get the money for them to avail some data so that they can survive the semester. As a solution to this, I will continue the donation drive of the former officers. The donation drive aims to give free data connections to the computer science students, but before getting the freebie the students will be needing to pass some requirements for the officer to sort out the students that are really in need. The funds of the donation drive will come from activities such as e-tournament and so on.",
        "As for some students, connection is not their problem but the lack of discussion in some lessons. This problem leads to the students having difficulty in answering some of their activities, and the worst case is that they will not be able to build a good foundation for the post-requisite subjects since computer science subjects are linked to each other. And I am presenting the “Aid Tutorial Class” to solve this problem, the Aid Tutorial Class will be led by the officers and some students with a higher understanding on a particular subject. The Aid Class is not compulsory, it is for some students that have a free-time in their schedule, the said class will also be recorded so that the students that want to have more understanding but can't attend the class can still have the chance to learn. In addition to the Aid Class, I am also thinking on having a e-Library that is only exclusive to computer science students. The library will contain different lectures and practice activities, the collection of lectures and activities will be covering the lessons from first year level up to the fourth year.",
        "As a future leader, I will always listen to the student's voice and concerns. By hearing and aiding student's side, it will not just benefit them but it will also help my growth as a leader.",
        "What would be your plans and your platforms since there are news about the implementation of limited face-to-face classes that will ensure the safety of your fellow Computer Science students?",
        "In the age of coronavirus disease 2019, returning to school has taken on a new meaning and a new set of concerns for parents and other caregivers. In the middle of the COVID-19 pandemic, schools must now balance the educational, social, and emotional requirements of their students and staff along with the health and safety measurements. Multiple tools should be employed to keep everyone healthy. COVID-19 vaccines are available to everyone who qualifies, as well as universal masking, physical separation, handwashing, and remaining at home while sick. To make it work, everyone must do their part to ensure that students and staff remain physically fit and together at school.",
        "If the school permits and the face-to-face class will really happen, I am planning some ideas that can help computer science students to stay shielded on the virus. First, is on creating DIY with my co-officer a hand sanitizer stands for each classroom. The students will not be touching the sanitizers but they will step on some mechanism for them to sanitize before entering their respective room. Next, is having the Sanitize as you go policy in the computer laboratory. Since we are sharing the same computer laboratory with other students, we must sanitize equipment that we use to avoid contaminating the hardware. Last, is having a friendly competition with the section in every year on who can keep their respective classrooms clean and sanitize. They can be rewarded with some prizes that are beneficial during the pandemic like facemasks, alcohol, alcohol spray containers, and etc.",
        "Recently, #LetEarthBreathe trends on different social media platforms. As a future student leader, what would be your step to do to encourage your fellow Komsay students to save our nature?",
        "Due to the increased use of plastics, oil, and other fossil fuels, the destruction of the Earth is speeding up. We should all pay attention to qualified scientists and cooperate with them. Why aren't we changing with the climate? Our only home, the Earth, is fading. Let's join forces to save it. It doesn't matter how small or minor your acts and efforts are, it is the start of something big so it does still help.",
        "As a future leader and also a people of this world, I am proposing to the professors and the institution this one simple act. It can also serve as a requirement for us to graduate. The idea is to have a day at university where every student will plant atleast one tree sapling in areas that trees are really needed. It is not just a requirement for our completion, but it is also a big help to the young generation to see the beauty of our home. Whatever our goal in life, let us not forget that we are living in the same world so let's work together to save our beautiful home.",
      ],
    },
  },
  {
    id: 13,
    firstName: "Aeren Jasper",
    middleName: "A",
    lastName: "Signo",
    img: "https://github.com/COSC70A-Group1/eboto-mo/blob/main/src/assets/imgs/election/candidates/PP/5%20-%20Auditor%20-%20Signo.png?raw=true",
    position: elections[0].positions[5],
    partylist: elections[0].partylists[2],
    votingCount: 0,
    significantAchievements: [
      "With honors during Senior High School years",
      "Among top students of Computer Science",
    ],
    leadershipAchievements: [
      "Cadet officer in JHS",
      "SSG committee in SHS",
      "STEM Club Representative",
      "Class Representative BSCS 1-2 2020-2021",
      "Public Relation Officer of CSSO 2021-2022",
    ],
    question: {
      question:
        "What are your advocacies that will help your fellow Computer Science students in this time of pandemic?",
      answer: [
        "COVID-19 lockdowns and school closures have a devastating impact on student's health, well-being, and learning. All students don't have the same privilege, many are still using data connection on attending classes and submitting their activities. They are struggling on to where they are going to get the money for them to avail some data so that they can survive the semester. As a solution to this, I will continue the donation drive of the former officers. The donation drive aims to give free data connections to the computer science students, but before getting the freebie the students will be needing to pass some requirements for the officer to sort out the students that are really in need. The funds of the donation drive will come from activities such as e-tournament and so on.",
        "As for some students, connection is not their problem but the lack of discussion in some lessons. This problem leads to the students having difficulty in answering some of their activities, and the worst case is that they will not be able to build a good foundation for the post-requisite subjects since computer science subjects are linked to each other. And I am presenting the “Aid Tutorial Class” to solve this problem, the Aid Tutorial Class will be led by the officers and some students with a higher understanding on a particular subject. The Aid Class is not compulsory, it is for some students that have a free-time in their schedule, the said class will also be recorded so that the students that want to have more understanding but can't attend the class can still have the chance to learn. In addition to the Aid Class, I am also thinking on having a e-Library that is only exclusive to computer science students. The library will contain different lectures and practice activities, the collection of lectures and activities will be covering the lessons from first year level up to the fourth year.",
        "As a future leader, I will always listen to the student's voice and concerns. By hearing and aiding student's side, it will not just benefit them but it will also help my growth as a leader.",
        "What would be your plans and your platforms since there are news about the implementation of limited face-to-face classes that will ensure the safety of your fellow Computer Science students?",
        "In the age of coronavirus disease 2019, returning to school has taken on a new meaning and a new set of concerns for parents and other caregivers. In the middle of the COVID-19 pandemic, schools must now balance the educational, social, and emotional requirements of their students and staff along with the health and safety measurements. Multiple tools should be employed to keep everyone healthy. COVID-19 vaccines are available to everyone who qualifies, as well as universal masking, physical separation, handwashing, and remaining at home while sick. To make it work, everyone must do their part to ensure that students and staff remain physically fit and together at school.",
        "If the school permits and the face-to-face class will really happen, I am planning some ideas that can help computer science students to stay shielded on the virus. First, is on creating DIY with my co-officer a hand sanitizer stands for each classroom. The students will not be touching the sanitizers but they will step on some mechanism for them to sanitize before entering their respective room. Next, is having the Sanitize as you go policy in the computer laboratory. Since we are sharing the same computer laboratory with other students, we must sanitize equipment that we use to avoid contaminating the hardware. Last, is having a friendly competition with the section in every year on who can keep their respective classrooms clean and sanitize. They can be rewarded with some prizes that are beneficial during the pandemic like facemasks, alcohol, alcohol spray containers, and etc.",
        "Recently, #LetEarthBreathe trends on different social media platforms. As a future student leader, what would be your step to do to encourage your fellow Komsay students to save our nature?",
        "Due to the increased use of plastics, oil, and other fossil fuels, the destruction of the Earth is speeding up. We should all pay attention to qualified scientists and cooperate with them. Why aren't we changing with the climate? Our only home, the Earth, is fading. Let's join forces to save it. It doesn't matter how small or minor your acts and efforts are, it is the start of something big so it does still help.",
        "As a future leader and also a people of this world, I am proposing to the professors and the institution this one simple act. It can also serve as a requirement for us to graduate. The idea is to have a day at university where every student will plant atleast one tree sapling in areas that trees are really needed. It is not just a requirement for our completion, but it is also a big help to the young generation to see the beauty of our home. Whatever our goal in life, let us not forget that we are living in the same world so let's work together to save our beautiful home.",
      ],
    },
  },
];

// admins
export const admins = [
  {
    id: 0,
    firstName: "Test",
    lastName: "Admin",
    email: "test.admin@cvsu.edu.ph",
    password: "admin123",
    elections: elections,
    candidates: candidates,
  },
];

// voters
export const votersData = [
  {
    id: 0,
    firstName: "Test",
    lastName: "Voter",
    email: "test.voter@cvsu.edu.ph",
    password: "u!fb#nY%",
    election: elections[0],
    hasVoted: false,
  },
  {
    id: 1,
    firstName: "Brice Brine",
    lastName: "Suazo",
    email: "bricebrine.suazo@cvsu.edu.ph",
    password: "c6GMl?Vm",
    election: elections[0],
    hasVoted: false,
  },
  {
    id: 2,
    firstName: "Rey Anthony",
    lastName: "De Luna",
    email: "reyanthony.deluna@cvsu.edu.ph",
    password: "9BwJY&l7",
    election: elections[0],
    hasVoted: false,
  },
  {
    id: 3,
    firstName: "Alex Kal-El",
    lastName: "Buenviaje",
    email: "alexkal-el.buenviaje@cvsu.edu.ph",
    password: "XIkv4$#M",
    election: elections[0],
    hasVoted: false,
  },
  {
    id: 4,
    firstName: "Aeren Jasper",
    lastName: "Signo",
    email: "aerenjaspera.signo.signo@cvsu.edu.ph",
    password: "81?oqqyX",
    election: elections[0],
    hasVoted: false,
  },
  {
    id: 5,
    firstName: "Merc Jan Rale",
    lastName: "Belanizo",
    email: "mercjanrale.belanizo@cvsu.edu.ph",
    password: "5jcS$pXi",
    election: elections[0],
    hasVoted: false,
  },
  {
    id: 6,
    firstName: "Lourielene",
    lastName: "Baldomero",
    email: "lourielene.baldomero@cvsu.edu.ph",
    password: "6Y$hmj#U",
    election: elections[0],
    hasVoted: false,
  },
  {
    id: 7,
    firstName: "John Lowell",
    lastName: "Mercado",
    email: "johnlowell.mercado@cvsu.edu.ph",
    password: "dCDk#?t1",
    election: elections[0],
    hasVoted: false,
  },
];
